version: 2.1
orbs: 
executors: 
  docker
  resource_class
  machine
  macos
  windows
  shell
  working_directory
  environment
commands:
  steps:
  parameters:
  description:
jobs:
  job_name:
    docker:
      -  image: postgres:14.2
         name:
         entrypoint:
         command: [--smallfiles]
         user:
         environment:
           ENV: CI
         auth:
           username: abc
           password: abcd
         aws_auth:
           oidc_role_arn: <your-iam-role-arn>
           aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
      - image: postgres:14.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: user
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    macos:
      xcode: "14.2.0"
    shell:
    parameters:
      name
      requires
      context
      type
      filters
      matrix
    steps:
      -  run: 
           command: |
            echo Running test
            mkdir -p /tmp/test-results
            make test
           name: test-run
           shell:
           environment:
           working_directory:
           no_output_timeout:
           when: always
      - run:
          name: Running X virtual framebuffer
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true
          - when:
              condition: <<parameters.custom_checkout>>
              steps:
                - run: echo "my custom checkout"
          - unless:
              condition: <<parameters.custom_checkout>>
              steps:
                - checkout
      - run:
          shell: /bin/sh
          command: |
            echo Running test
            mkdir -p /tmp/test-results
            make test
    working_directory:
    parallelism:
    environment:
    branches:
    resource_class: small
